spring:
  profiles:
    active: mongo

---
spring:
  profiles: test
  r2dbc:
    url: r2dbc:mysql://localhost:3306/movie
    username: root
    password: root


---
spring:
  profiles: mongo
  r2dbc:
    url: r2dbc:mysql://localhost:3306/movie
    username: root
    password: root

server:
  port: 8082
---
spring:
  profiles: dev
  r2dbc:
    url: r2dbc:mysql://localhost:3306/movie
    username: root
    password: root
logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG

server:
  error:
    include-stacktrace: on_param
  port: 8080
#http://localhost:8080/movie/55?trace=true (?trace flag returns the stacktrace)

---
spring:
  profiles: prod
  r2dbc:
    url: r2dbc:mysql://localhost:3306/movie
    username: root
    password: root
logging:
  level:
    org:
      springframework:
        data:
          r2dbc: INFO

server:
  error:
    include-stacktrace: on_param
  port: 8081
#http://localhost:8080/movie/55?trace=true (?trace flag returns the stacktrace)

---
spring:
  profiles: k8s
  r2dbc:
    url: r2dbc:mysql://localhost:3306/movie
    username: root
    password: root
logging:
  level:
    org:
      springframework:
        data:
          r2dbc: INFO

server:
  error:
    include-stacktrace: on_param
  port: 8082
#http://localhost:8080/movie/55?trace=true (?trace flag returns the stacktrace)

