spring:
  profiles:
    active: dev

---
spring:
  profiles: test


---
spring:
  profiles: dev

#running embedded

server:
  port: 8080

---
spring:
  profiles: prod
logging:
  level:
    org:
      springframework:
        data:
          r2dbc: INFO

server:
  error:
    include-stacktrace: on_param
  port: 8081
#http://localhost:8080/movie/55?trace=true (?trace flag returns the stacktrace)

---
spring:
  profiles: k8s
logging:
  level:
    org:
      springframework:
        data:
          r2dbc: INFO

server:
  error:
    include-stacktrace: on_param
  port: 8082
#http://localhost:8080/movie/55?trace=true (?trace flag returns the stacktrace)

