GET http://localhost:8080/movie/list

###

GET http://localhost:8080/movie/2

### not found

GET http://localhost:8080/movie/55

###

POST http://localhost:8080/movie
Content-Type: application/json

{
  "name": "Mortal Combat"
}

###

###

POST http://localhost:8080/movie/batch
Content-Type: application/json

[
  {
    "name": "karate kid"
  },
  {
    "name": "Karate kid II"
  },
  {
    "name": ""
  }
]

###

PUT http://localhost:8080/movie
Content-Type: application/json

{
  "id": 8,
  "name": "Mortal Combat II"
}

###


DELETE http://localhost:8080/movie/8
Content-Type: application/json

###

GET http://localhost:8080/movie/title/matrix

###