GET http://localhost:8080/movie/list

###

GET http://localhost:8080/movie/2

### not found

GET http://localhost:8080/movie/55

###

POST http://localhost:8080/movie
Content-Type: application/json

{
  "name": "Mortal Combat"
}

###


PUT http://localhost:8080/movie
Content-Type: application/json

{
  "id": 8,
  "name": "Mortal Combat II"
}